### ISSUE TITLE
[Spike] Automate Accessibility Checks

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/police_data_manager#104]
## Summary
We want to automate accessibility checks to make sure that new things we do don't introduce new issues

https://www.thoughtworks.com/radar/tools/axe-core

### In Scope
 - run axe dev tools when the pipeline runs? 
 - document tools used

### Acceptance Criteria
Given we push code
When the pipeline runs
Then we get an accessibility test score/result

**Comment by isabelolson** [comment]
Findings: https://docs.google.com/document/d/1Y5GHiErLhwUHCyYT3FaNhbX2HsPukqyfhE8Q87AN6c4/edit?usp=sharing
