### ISSUE TITLE
[Spike] E2E Tests - fix 'em or replace 'em?

### ISSUE THREAD

**Issue by isabelolson** [PublicDataWorks/police_data_manager#110]
3 days

### the issue
Our e2e tests are flaky in CircleCI (fail for no reason and need to rerun multiple times to pass).

The question: do we fix the flaky tests or replace them with contract tests?

## task
take the last two steps of the letter flow (edit, approve) and add contract tests - if it is more stable, we can continue with more contract tests?

Is there anything that these tests are missing vs E2E tests?

Metrics:
1. test coverage
2. ease of implementation
3. letter generation flow coverage

**Comment by andrew-rist-tw** [comment]
Calling this done.  Will raise new pact cards once we get a solution to the yield issue
