### ISSUE TITLE
Case notes being recorded incorrectly in case history

### ISSUE THREAD

**Issue by jordanngtw** [PublicDataWorks/police_data_manager#93]
# BUG:

### Business Context:
When you add a case note to a case and then look at the case history, the entry for the addition of the case note shows undefined and N/A (see screenshot), which is not ideal

### To recreate
1. comment on a case
2. go to case history
3. find that comment
4. it will say "undefined: N/A"

### Expected Behavior:
the case note should create a case history entry that looks like this in the "Details column":

**Action**: Pulled docket from the court website
**Action Taken At**: May 02, 2019 2:18:00 PM CDT

to summarize, things to fix:
1. Undefined N/A
2. formatting (basically getting rid of the repeated information and making it so everything is not so bold)

### Checklist (should be reviewed before grooming as the BA or Pair are writing the card—NOT reviewed for the first time at grooming)
0. Discuss the technical implementation of this card.
1. Discuss how this feature would be included in or affect the Audit Log.
2. In respect to security, what could go wrong? Brainstorm threats using STRIDE model, especially if this card introduces a new technical architecture or design pattern. (TIMEBOX: 7 mins) https://docs.google.com/document/d/18AFl1d3SRieI4d_8R3GyEazqQOycLNDHGN_vOYIHuiE/edit#heading=h.aio9zb5j63wl
3. Ensure any open questions have been resolved with stakeholders.
4. Determine if documentation should be referenced or created.
5. Ensure to include all necessary mockups to this card.
6. Discuss what success/failure user feedback messages would be present, if any occur (front end/back end).
7. Discuss why this feature would not be implemented behind a toggle / what would happen if this card was partially done while a release branch was being cut.
8. If this card is part of a sequence of cards, discuss if this card should be blocked until the testing of previous  cards in the sequence have been finished.
9. Have we added edge cases as ACs that we're considered from a QA perspective
10. Does this card overlap with any entities outlined in [API Housekeeping](https://www.pivotaltracker.com/story/show/173963545)?  

**Notes:**

**Comment by jordanngtw** [comment]
![Screen Shot 2022-01-12 at 3 17 11 PM](https://user-images.githubusercontent.com/86383902/149224588-779ae2e0-4d40-4d01-868e-227c6d676e54.png)

**Comment by andrew-rist-tw** [comment]
in CaseHistoryDetails, it's breaking down model description and mapping each element of that array, but the first element is empty
